Additional user info prompts
jordyob03/TripTailor pull request #14
Opened 2024-10-10 11:53 UTC by allymreid

- Added name prompt to profile creation page
- Added DOB to sign up page

- Added password/username criteria:
Username:
- Less than 24 char
- No whitespace
- No special characters except_

Password:
- Must contain number
- No whitespace
- 8-24 chars

2024-10-11 22:36 UTC, AbdulTur requested changes
Looks great. is it possible to add a change to the valid password function to also check if password contains atleast 1 letter and also contains a special character like, !@#*()_-+, otherwise looks good.

2024-10-11 22:45 UTC, AbdulTur requested changes

2024-10-11 22:45 UTC, AbdulTur commented on frontend/src/pages/UserSignup.js
> -
Also it looks like the api handling code was deleted. That needs to stay there

2024-10-18 21:48 UTC, AbdulTur approved these changes
LGTM Well done!!

2024-10-20 16:56 UTC, WyrdWyn4 approved these changes
LGTM, Great Job!

2024-10-20 16:56 UTC, merged